name: CD

# 주석 처리된 원본 내용
# on:
#   workflow_dispatch:
#   pull_request:
#     types: [closed]
#     branches: [develop]

on:
  pull_request:
    branches: ["develop"]
  workflow_dispatch:

jobs:
  deploy:
    # 주석 처리된 원본 조건
    # if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/dev:latest

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            docker pull ${{ secrets.DOCKER_USERNAME }}/dev:latest
            docker stop app || true
            docker rm app || true
            docker run -d --name app -p 80:80 ${{ secrets.DOCKER_USERNAME }}/dev:latest
            docker image prune -f
          EOF

